version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    container_name: netology_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: demo_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_pass
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d demo_db"]
      interval: 5s
      timeout: 3s
      retries: 5